baseURL = "https://life.urakalee.me/"
languageCode = "zh-cn"
title = "Binary Life"
theme = "PaperMod"
paginate = 10

[params]
  author = "Uraka Lee"
  description = "诗人 方法论者 喝汤族 微微爸"
  defaultTheme = "light"
  disableThemeToggle = true
  showShareButtons = false
  showReadingTime = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showToc = true

  [params.homeInfoParams]
    Title = "Binary Life"
    Content = "诗人·方法论者·喝汤族·微微爸"

  [[params.friendLinks]]
    name = "我的公众号"
    qrcode = "/images/wechat_blog.jpg"
    desc = "扫码关注"
  #[[params.friendLinks]]
  #  name = "示例博客"
  #  url = "https://example.com"
  #  desc = "一个示例友链"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 30
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.alerts]
        enable = true
  [markup.highlight]
    noClasses = false
    lineNos = false
